### ISSUE TITLE
请问如果插入原生video，怎么在js里面实现onplay、ontimeupdate等事件的监听？

### ISSUE THREAD

**Issue by Pasoul** [lionvoom/WeAppTongCeng#1]

**Comment by lionvoom** [comment]
这个需要跟JS端配合实现, 比如微信JS端实现了WeixinJSBridge类, 供iOS/安卓通过js注入的方式调用JS端. 比如:
1. onplay消息: NSString *javaScriptString = @"WeixinJSBridge.subscribeHandler('onVideoPlay', {"videoPlayerId": 14426,"data": "{}"}, 0, {'nativeTime': 1598945396943});";
2. [WKWebView -evaluateJavaScript:javaScriptString completionHandler:...]; //webview注入js, 也就是原生调用JS端

⚠️不过, 在小程序底层实现是分'逻辑层' 和 '页面层', WeixinJSBridge.subscribeHandler 是在逻辑层实现的.
